export enum OrderEventType{
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_AGGREGATED = 'ORDER_AGGREGATED',
    ORDER_DISPATCHED = 'ORDER_DISPATCHED',
    ORDER_DELIVERED = 'ORDER_DELIVERED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    ORDER_COMPLETED = 'ORDER_COMPLETED',
}                   